#Macros
__LINE__ # current line number (int)
__FILE__ # current file (char*)
__DATE__ # current data (as returned by ctime) (char*)
__TIME__ # current time (char*)
__FUNC__ # name of current function??
__DEBUG__ # true if the debug flag "-d" has been passed to the compiler

# Compiler definition
__COMPILER_DEFINITION__(definition, value) # Updates the table of compiler definitions with a certain value
    # Compiler definitions
    # VECTOR_MATH: bool - If set to true, compiler will perfom elementwise arithmetic operations(automatically sets matrix math to be false)
    # MATRIX_MATH: bool - If set to true, compiler will perform matrix operations (automatically sets vector math to be false)
    # MATH_MODE: ture - If set to true, compiler will enable optimizations for math operations, required for vector_math and matrix_math
    # INLINE: bool - If set to true, compiler will inline when possible for file, overrides compiler flags 