identifier = 
    identifier-non-digit
    identifier identifier-non-digit
    identifier digit 

identifier-non-digit = 
    [a-ZA-Z0-9] | "-" | "_"

digit = 
    [0-9]

literal = 
    bool-literal
    pointer-literal
    character-literal
    string-literal
    int-literal
    float-literal

bool-literal =
    "true"
    "false"

pointer-literal =
    "nilptr"

character-literal = 
    ' character '

character = 
    basic-char 
    escape-sequence

basic-char = 
    any character except newline and ''

escape-sequence = 
    '\\' escape-sequence-char 

escape-sequence-char = 
    'r' | 't' | 'f' | 'v' |'n' | 'a' | 'b'

string-literal =
    " [character-sequence] "

character-sequence = 
    s-char 
    character-sequence s-char 

s-char =
    basic-s-char 
    escape-sequence

int-literal = 
    digit-sequence [int-literal-suffx]

digit-sequence = 
    digit 
    digit-sequence digit

int-literal-suffix =
    's' | 'S' | 'l' | 'L'

float-literal = 
    fractional-constant [exponential-part] [floating-point-suffix]
    digit-sequence exponential-part [floating-point-suffix]

fractional-constant = 
    [digit-sequence] '.' digit-sequence 
    digit-sequence '.'

exponential-part = 
    'e' | 'E' [sign] digit-sequence

sign = 
    '+' | '-'

floating-point-suffix - 
    'f' | 'F'

operators =

keywords =
